
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/producto.js'
export type * from './models/usuario.js'
export type * from './models/pedido.js'
export type * from './models/pedido_item.js'
export type * from './commonInputTypes.js'